version: '3.8'

services:
  frontend:
    build: ./Frontend
    container_name: nextjs_app
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"

  backend:
    build: ./Backend
    container_name: fastapi_app
    volumes:
      - ./Backend:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
