version: '3.8'

services:
  obs-python-app:
    build: .
    container_name: obs_python_app
    volumes:
      - .:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
      - OBS_HOST=192.168.0.79
